services:
  chromadb:
    image: chromadb/chroma:0.5.20
    env_file:
      - .env
    volumes:
      - chroma:/chroma/chroma/
    ports:
      - '${PORT_EXTERNAL_CHROMADB}:8000'

  ollama:
    build: .
    entrypoint: sh ./docker-entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./:/app:cached
      - ollama:/root/.ollama
    ports:
      - '${PORT_EXTERNAL_OLLAMA}:11434'

  open_webui:
    image: ghcr.io/open-webui/open-webui:main
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
      - open_webui:/app/backend/data
    ports:
      - '${PORT_EXTERNAL_OPEN_WEBUI}:8080'

volumes:
  ollama:
  open_webui:
  chroma:
